import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { GetServerSideProps } from "next";

import Button from "@mui/material/Button";
import client from "../apollo-client";
import { GET_POKEMON_LIST } from "../graphql/queries/getPokemonList";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Button variant="contained">Contained</Button>
      </main>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const { data } = await client.query({
    query: GET_POKEMON_LIST,
    variables: {
      limit: 10,
      offset: 0,
    },
  });
  
  return {
    props: {}, // will be passed to the page component as props
  };
};

export default Home;
